spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waiter-open-platform
    username: root
    password: camellia
  redis:
    port: 6379
    host: localhost
    database: 0
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
waiter:
  client:
    # 在 dev 中配置
    access-key: ba349d97149eaf5ba81d24afc9161fa6
    secret-key: e450cd3a2c9050a659eabd617d042acd